### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by 0sugo** [0sugo/tv-maze#21]
- https://github.com/0sugo/tv-maze/projects/1.

- Hello reviewer, this repository has two contributors: @rosemutai  and @0sugo

**Comment by Shisui6** [comment]
Hi @0sugo and @rosemutai, 

# Approved 🪄
Your project is complete! Congratulations! 🎉 

## Highlights
- Kanban board setup correctly ✅
- All tasks are assigned ✅

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
